title: <p align="center"> Palak Jindal </p>
logo: /assets/img/1516696491979.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/palak-jindal-578b9279/">LinkedIn</a> |
  <a href="https://github.com/palak24jindal">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  I'm learning Machine leanrning and Artificial Intelligence from IIIT Banglore and LJMU.
  <br>
  </p>



theme: jekyll-theme-minimal
